---
- name: Create MDB Overlays
  command: >
    /usr/local/bin/slapd-create-overlay "{{ slapd_ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ slapd_olc_rootdn }}"
    "olcDatabase={2}mdb,cn=config"
    "{{ item.key }}" "{{ item.value.objectClass }}"
  environment:
    bindpw: "{{ slapd_olc_rootdn_password | mandatory }}"
  register: out
  changed_when: "'CHANGED' in out.stdout"
  with_dict: "{{ slapd_mdb_overlays }}"
  when: "slapd_mdb_overlays is not undefined"

