#!/bin/bash -e

# This script is supposed to create a monitor database if it doesn't exist yet.

set -o nounset
umask 177

# Parameters
socket="ldapi://${1}"
binddn="${2}"
# bindpw via env variable

# See how it currently looks
set +e
builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "olcDatabase={1}monitor,cn=config" -s base "dn"
status="${?}"
set -e

# Does the object already exist?
if [ "${status}" != 32 ]; then
	exit "${status}"
fi

# Create it
cat << EOF > /dev/shm/addmon.ldif
dn: olcDatabase={1}monitor,cn=config
objectClass: olcMonitorConfig
olcDatabase: {1}monitor
EOF
builtin echo -n "${bindpw}" | ldapadd -H "${socket}" -D "${binddn}" -y /dev/stdin -f /dev/shm/addmon.ldif
rm -f /dev/shm/addmon.ldif
echo "CHANGED"
