#!/bin/bash -e

# This script is supposed to create an MDB database if it doesn't exist yet.

set -o nounset
umask 177

# Parameters
socket="ldapi://${1}"
binddn="${2}"
# bindpw via env variable
suffix="${3}"
dbDir="${4}"

# See how it currently looks
set +e
builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "olcDatabase={2}mdb,cn=config" -s base "dn"
status="${?}"
set -e

# Does the object already exist?
if [ "${status}" != 32 ]; then
	exit "${status}"
fi

# Create it
cat << EOF > /dev/shm/addmdb.ldif
dn: olcDatabase={2}mdb,cn=config
objectClass: olcMdbConfig
olcDatabase: {2}mdb
olcSuffix: ${suffix}
olcDbDirectory: ${dbDir}
EOF
builtin echo -n "${bindpw}" | ldapadd -H "${socket}" -D "${binddn}" -y /dev/stdin -f /dev/shm/addmdb.ldif
rm -f /dev/shm/addmdb.ldif
echo "CHANGED"
